# Generated by Django 4.2.16 on 2024-09-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryType', models.CharField(choices=[('Супы', 'Супы'), ('Пельмени', 'Пельмени'), ('Десерты', 'Десерты'), ('Рецепты первых блюд', 'Рецепты первых блюд'), ('Рецепты вторых блюд', 'Рецепты вторых блюд'), ('Рецепты третьих блюд', 'Рецепты третьих блюд')], max_length=20, verbose_name='Категория')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Рецепты',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
